name: 機能要求 / Feature Request
description: 新機能の追加や既存機能の改善を提案する
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 機能要求テンプレート
        新しい機能の追加や既存機能の改善提案にご利用ください。

  - type: textarea
    id: feature-summary
    attributes:
      label: 機能の概要
      description: 追加・改善したい機能について簡潔に説明してください
      placeholder: 例）Terraformコード生成時に複数のAWSリージョンに対応したい
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: カテゴリ
      description: この機能要求のカテゴリを選択してください
      options:
        - UI/UX改善
        - AWS新サービス対応
        - Streamlit機能追加
        - Terraform生成改善
        - MCP統合
        - パフォーマンス改善
        - セキュリティ強化
        - その他
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 背景・動機
      description: なぜこの機能が必要だと思うのか、どのような問題を解決するのかを説明してください
      placeholder: |
        例）
        - 現在は単一リージョンでしかTerraformコードを生成できない
        - マルチリージョン構成が必要なプロジェクトで手動修正が必要
        - 災害復旧対応のために複数リージョン展開が求められている
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 提案する解決策
      description: どのような実装・改善を想定しているか具体的に説明してください
      placeholder: |
        例）
        - リージョン選択のドロップダウンをUIに追加
        - システムプロンプトにマルチリージョン対応の指示を追加  
        - Terraformテンプレートにregion変数を組み込み
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の重要度を選択してください
      options:
        - 低 (Nice to have)
        - 中 (Should have)  
        - 高 (Must have)
        - 緊急 (Critical)
      default: 1
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 受け入れ条件
      description: この機能が完成したと判断できる条件を列挙してください
      placeholder: |
        例）
        - [ ] UIでリージョンを選択できる
        - [ ] 選択したリージョンに対応したTerraformコードが生成される
        - [ ] マルチリージョン構成のベストプラクティスが反映される
        - [ ] 既存機能に影響がない

  - type: textarea
    id: related-pages
    attributes:
      label: 関連ページ・機能
      description: この機能要求に関連するページや既存機能があれば記載してください
      placeholder: |
        例）
        - Terraformコード生成ページ
        - AWS構成提案チャット
        - プロンプト設定ファイル

  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: その他、参考になる情報があれば記載してください（スクリーンショット、参考リンクなど）